### ISSUE TITLE
ES6 module 

### ISSUE THREAD

**Issue by thiagogcm** [mapbox/mapbox-sdk-js#130]
Cannot import this library in a angular2 app

`import { MapboxClient } from 'mapbox'; `

results in Cannot find module 'mapbox'

**Comment by tmcw** [comment]
Mind trying

```js
import MapboxClient from 'mapbox';
```

We'd need to know what bundler you're using (webpack?) but you should expect a single default export rather than a named export from this module.

**Comment by thiagogcm** [comment]
Same error

Yes, I'm using webpack (it's an angular-cli App)

No problem with mapbox-gl btw

**Comment by tmcw** [comment]
And you've run `npm install mapbox`? Do you see a `mapbox` directory in `node_modules`? Did the installation produce any errors?

**Comment by thiagogcm** [comment]
Yes
`var MapboxClient = require('mapbox');` works as expected

but cannot import like the other libs

**Comment by Wykks** [comment]
`import MapboxClient from 'mapbox';` works fine on angular-cli

How about sub import ?

**Comment by davidtheclark** [comment]
Closing as stale. 

This should not be a problem since this module [uses `module.exports`](https://github.com/mapbox/mapbox-sdk-js/blob/22aba19e3f8e9f263737f79ae366885f22f908c6/lib/mapbox.js#L59) the same way as anything else. I suspect that the original issue was the result of a build process mixup.
