### ISSUE TITLE
Make pagination easy

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-sdk-js#137]
For our endpoints that support pagination, we have a `next` header. This header can be added to `start` in the pagination options to go to the next page.

It would be cool if callbacks called by listing endpoints used a `function(err, data, next) {}` signature where next is a function that takes a callback only. When there are no more pages, next should be undefined.

**Comment by tmcw** [comment]
I implemented multi-page support with Link headers in https://github.com/tmcw/got-links , could use that as an example.

**Comment by andrewharvey** [comment]
How about treating this transparently to the user? The Styles API seems to limit results to 12 per page, if `client.listStyles`simply return all styles it would be much simpler.

**Comment by andrewharvey** [comment]
@scothis Do you have any advice on the best way to do this, perhaps in the context of `rest`? I noticed the HATEOAS interceptor does very similar things but I couldn't manage to get it working.

https://github.com/mapbox/mapbox-sdk-js/commit/f55debb555beeef8d143b5a50fce393966b7dc43 is where I'm up to but it's not working. Any help would be much appreciated.

I know for dataset features endpoints, transparent pagination might not be best, but for things like styles or tilesets it makes things a lot easier on the client side.

**Comment by mcwhittemore** [comment]
> The Styles API seems to limit results to 12 per page

Just FYI, this limit is based on the size of the style. If you had a bunch of really small styles you'd get more and if you had many very big style you'd get less. 

> How about treating this transparently to the user?

I'd be down for providing an opt-in option for requests. Something like `{getAll: true}` but it should be off for all endpoints by default. We don't want a situation where some endpoints work one way and other work another way.

**Comment by scothis** [comment]
@andrewharvey rest.js has the facilities to parse out the Link header for pagination. The main issue is that we don't expose this capability in clean way. The question becomes how to expose pagination.

I'm a bit uneasy about offering an automatic tool to fetch all pages. These tools are helpful in the optimistic case, but will cause significant trouble when the user's expectations don't quite align. If a user really wants to do this, they can implement it themselves.

We can't implement the original suggestion of `(err, data, next) => {}` as the callback signature because the current signature is `(err, data, res) => {}`. Adding yet another arg is doable, but doesn't do anything to help users using Promises instead of callbacks.

I think the right way to handle this is to include a `.next([callback])` or `.nextPage([callback])` method on the response object when there is another page available. rest.js has a more generic notion of a `.follow(relationship)` method.

I'll take a crack at a quick PR.

**Comment by andrewharvey** [comment]
> I'd be down for providing an opt-in option for requests. Something like {getAll: true} but it should be off for all endpoints by default. We don't want a situation where some endpoints work one way and other work another way.

If unpaginating results isn't the default then I feel the documentation should make this really clear as I can see it becoming a big gotcha where users aren't expecting results to be paginated.

For all the use cases I'm working on at the moment I want unpaginated results.

> @andrewharvey rest.js has the facilities to parse out the Link header for pagination. The main issue is that we don't expose this capability in clean way. The question becomes how to expose pagination.

Thanks @scothis. After studying a few different rest interceptors and with some help from @mcwhittemore I was able to get an unpaginate interceptor working https://github.com/mapbox/mapbox-sdk-js/compare/transparent-pagination which I'm really happy with.

> I think the right way to handle this is to include a .next([callback]) or .nextPage([callback]) method on the response object when there is another page available. rest.js has a more generic notion of a .follow(relationship) method.

To get a list of Styles in an account and count how many there are with my transparent pagination branch from https://github.com/mapbox/mapbox-sdk-js/compare/transparent-pagination it's very easy from the user's perspective:

```
mapboxClient.listStyles((err, styles) => {
   // styles
   // styles.length
});
```

@scothis With your suggested option what would the user have to do to achieve the same as above? I couldn't quite work it out from the documentation from https://github.com/mapbox/mapbox-sdk-js/pull/159/files

I'm in favour as making all the complexity hidden so that users who simply want to get a list off all the styles or other in an account don't need to deal with pages unless they want to.

What's wrong with https://github.com/mapbox/mapbox-sdk-js/compare/transparent-pagination as a solution here?

**Comment by andrewharvey** [comment]
@scothis I think the Mapbox API might need to set the [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) header on API responses with pagination to include the Link header for the browser?

Is this right?

Trying the following in the browser doesn't include the Link header needed to follow response pages.
```
var request = new XMLHttpRequest();
request.open("GET", "https://api.mapbox.com/styles/v1/USERNAME?access_token=SK_ACCESS_TOKEN", true);
request.send();
request.onreadystatechange = function() {
  if(this.readyState == this.HEADERS_RECEIVED) {
    console.log(request.getAllResponseHeaders());
  }
}
```

**Comment by scothis** [comment]
> I think the Mapbox API might need to set the Access-Control-Expose-Headers header on API responses with pagination to include the Link header for the browser?

Yea... nice catch. I'll work to get that header exposed for all of our listing endpoints.

> What's wrong with https://github.com/mapbox/mapbox-sdk-js/compare/transparent-pagination as a solution here?

After a quick look at your code, it looks like a good solution. The bigger issue with unpaginating by default is that some users have very, very large listings of resources (many millions). Attempting to blindly load all of those items would be wildly inefficient. I'm not a fan of setting defaults that can break in horrific ways.

I agree that the documentation needs to be clear that pagination is the default for listings.

**Comment by andrewharvey** [comment]
> After a quick look at your code, it looks like a good solution. The bigger issue with unpaginating by default is that some users have very, very large listings of resources (many millions). Attempting to blindly load all of those items would be wildly inefficient. I'm not a fan of setting defaults that can break in horrific ways.

Fair point. It would be nice to make things simple for use cases that just want a whole list and don't want to deal with pagination, but also expose the option to get results in pages at a time.

**Comment by scothis** [comment]
@andrewharvey I merged support for easy loading of single pages. We can continue the discussion here about making it easier to load all pages (or all pages up to some limit).

**Comment by andrewharvey** [comment]
>>I think the Mapbox API might need to set the Access-Control-Expose-Headers header on API responses with pagination to include the Link header for the browser?
>
> Yea... nice catch, it's exposed on some endpoints but not all. I'll work to get that header exposed universally.

@scothis How is this going?

**Comment by andrewharvey** [comment]
>>I think the Mapbox API might need to set the Access-Control-Expose-Headers header on API responses with pagination to include the Link header for the browser?
>
>Yea... nice catch, it's exposed on some endpoints but not all. I'll work to get that header exposed universally.

Just noting for the record, this is fixed now.

**Comment by Soliah** [comment]
I'm finding that the datasets endpoint is not setting the appropriate value for `Access-Control-Expose-Headers`. I'm getting empty values for this header which causes the library to return `null` for the `nextPage`. I'll be raising a support ticket for this.

**Comment by andrewharvey** [comment]
I'm finding it's easier to abstract away dealing with pagination. This is what I've done https://github.com/alantgeo/mapbox-backup/blob/master/mapbox-transparent-pagination.js.

Ideally I'd override the function names directly so you just need one include to make all endpoints return unpaginated responses.

**Comment by scothis** [comment]
@Soliah @andrewharvey the CORS headers should be set correctly now, let me know if you run into other issues with them.

**Comment by davidtheclark** [comment]
The newly published `@mapbox/mapbox-sdk` has a `Request#eachPage` function that makes pagination easy.
