### ISSUE TITLE
Replace Distance API with Directions Matrix API

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-sdk-js#161]
Which returns travel times from many points: https://www.mapbox.com/api-documentation/#directions-matrix. Directions API is now deprecated.

**Comment by bshyong** [comment]
@scothis can we get this added? We have a paid account but cannot use the Matrix API from this npm package. Mapbox support says we cannot use the directions API to get driving times.

**Comment by geografa** [comment]
@bshyong Distance API is now Matrix API https://www.mapbox.com/api-documentation/#matrix. Are you able to use this?

**Comment by bshyong** [comment]
@geografa Yes, I can manually use the Matrix API in the meantime

However, since we are using the npm library for other calls as well, it would be a little cleaner to use the library. I'd prefer to use this library if there plans to add the Matrix API in the near future.

The distance API included is currently deprecated 
https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/services/distance.js

**Comment by geografa** [comment]
@bshyong 👍  I'm picking this up here https://github.com/mapbox/mapbox-sdk-js/pull/172#issuecomment-306865193
