### ISSUE TITLE
Jasmine tests are failing due to usage of rest dep method fullyQualify

### ISSUE THREAD

**Issue by gurre** [mapbox/mapbox-sdk-js#182]
I'm getting the error mentioned here: https://github.com/cujojs/rest/issues/135

`TypeError: Cannot read property 'origin' of undefined`

> fullyQualify is only supported in browsers, as in Node there isn't a base url to be relative to. My guess is that you have a partially polyfilled window.location object. If the location object is completely missing the method will shortcut itself.

My suggestion is trying to avoid methods depending on the Window-object.

I'm going to use axios instead of this lib. Your URLs are properly structured anyway.

**Comment by davidtheclark** [comment]
@gurre: Sorry for the delay in response. If you are using this package in Node, you *should* be getting the Node version of rest. Can you provide more details about your usage that hit this error? 

Or, if that would be too much trouble since it's been a while, we can close this issue and re-open if it arises again.

**Comment by gurre** [comment]
Well it depends on if you want to fix it by ditching UrlBuilder.

**Comment by davidtheclark** [comment]
@gurre: I'm not sure I understand your response. What is the problem you are having with rest's UrlBuilder?
