### ISSUE TITLE
Geocode Reverse API documentation Typo

### ISSUE THREAD

**Issue by vikneshwar** [mapbox/mapbox-sdk-js#183]
In Reverse geocoding example, the variable used to create client object is wrong . It should be **MapboxClient** instead of MapboxGeocoding but however, it depends upon the variable name you use to **require('mapbox')**. But someone reading the documentation would get confused for a second .

**Comment by andrewharvey** [comment]
I assume you're talking about here https://github.com/mapbox/mapbox-sdk-js/blob/master/API.md#geocodereverse.

I wouldn't say it's wrong because as you say it depends on the variable name you use.

One way to use mapbox-sdk-js is `var MapboxClient = require('mapbox');` but also as noted at https://github.com/mapbox/mapbox-sdk-js#sub-requiring-individual-services it's common to just require the individual services you need, like this https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/mapbox.js.

Hence if you do `var MapboxGeocoding = require('mapbox/lib/services/geocoding');` then the example makes sense.

However since all the other examples use MapboxClient then it makes sense to be consistent, so agree with changing this.

Did you want to submit a PR? The example is defined in the source at https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/services/geocoding.js#L173 and the API.md is generated via the package.json docs script.
