### ISSUE TITLE
New validation lib doesn't reject unwanted properties

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-sdk-js#239]
@kepta I noticed that the new validation lib does not reject unwanted properties. For example, I can send a request to `Datasets#listDatasets` with a `waypoints` property, and there's no error.

Do you think we should make it more strict, so *only* properties specified in the schema are allowed? Or do you think we should keep it loose?

**Comment by kepta** [comment]
Ya, I believe that was intentional on my side to follow the lose nature of `prop-type`. But I can see why that would be a problem. 
We can do something similar to airbnb's [forbidExtraProps](https://github.com/airbnb/prop-types). 

This would be another validator similar to `v.shapeOf` but which forbids any extra properties.

**Comment by davidtheclark** [comment]
> that was intentional on my side

Good choice 👍 That enables you to pass around objects without validating every single property every time. I think that's a good default.

For our case in this SDK, a `strictShapeOf` would be great, so users are aware when they are passing unnecessary properties.

**Comment by davidtheclark** [comment]
I added a `v.strictShape` higher-order validator to fusspot, so this issue is actionable.
