### ISSUE TITLE
Pre-bundled files static not initialized

### ISSUE THREAD

**Issue by MorganDbs** [mapbox/mapbox-sdk-js#251]
Hi, I'm using Pre-bundled files and the doc says it's "initializes all the services", but when I do 
```js
 mapboxClient.static
```

It's giving me "undefined". Any clues ?

**Comment by davidtheclark** [comment]
Thanks for the report, @MorganDbs! It was an oversight on our part — added new services, forgot to add them to the UMD bundle, didn't find out since we didn't use that bundle. In #252 I added the missing services (there was more than just the Static API) and added a new test to ensure we don't forget to add services to the UMD bundle in the future.

**Comment by davidtheclark** [comment]
Fix released in 0.1.3. Hope that solves your problem, @MorganDbs!

**Comment by davidtheclark** [comment]
@MorganDbs Yeah, 0.1.3 should be released on npm, too.
