### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by devlocalca** [mapbox/mapbox-sdk-js#290]
I want to verify if this installed correctly, it did not print "BIG SUCCESS!!!" as the last statement just before returning me to the shell after running the install command.

Environment
```
Windows 10
cygwin
node: v10.13.0
npm 6.4.1
```
---
I run:
`npm install @mapbox/mapbox-sdk`

-- console print out
```
npm WARN saveError ENOENT: no such file or directory, open 'H:\home\code\mapbox\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'H:\home\code\mapbox\package.json'
npm WARN mapbox No description
npm WARN mapbox No repository field.
npm WARN mapbox No README data
npm WARN mapbox No license field.

+ @mapbox/mapbox-sdk@0.4.1
updated 1 package and audited 362 packages in 37.981s
found 0 vulnerabilities
```
Is this exactly what I should expect after installation?

---
Are those warnings of concern?
Do I need anything (dependencies) from mapbox installed like: 
`$npm install mapbox-gl --save`   ??

I could not get that to work with node.js 10, it spewed 71 lines of errors and got stuck never returning to the command prompt after 12 hours.
--
Also is this code: mapbox-sdk-js a Mapbox product or from third party developers?
Is anyone aware of a SDK in other languages (have mutiple team members on various layers wanting to interact with Mapbox in other languages (all server side)

--
Requirement:  I have a requirement to read a file full of street addresses and need to get the latitude, longitude and store all three in a db together (street address, coordinates), and nothing more on the server side.  I want to call Mapbox geo functions to do this on the server side, there is no web component with this specific task, there will be later, but I just want to interact on the server side if any examples can be provided or pointers to do this with mapbox-sdk-js.

Thank you very much for your help.

devlocalca@gmail.com

**Comment by davidtheclark** [comment]
Hi @devlocalca. I'll try to address each of your questions or problems:

- Looks like your npm command successfully installed the `@mapbox/mapbox-sdk` package. All the warnings are about installing npm packages into a directory that does not contain a `package.json` file. I suggest reading more about Node and npm to understand the details of that.
- You do not need to install mapbox-gl in order to use mapbox-sdk-js. Mapbox GL JS renders maps; Mapbox SDK JS helps make calls to [Mapbox's APIs](https://mapbox.com/api-documentation/).
- "I could not get that to work with node.js 10" ... I'm not sure what this is referring to. What is not working, and what errors are occurring? If they're not related to this library — maybe they're about mapbox-gl? — I suggest [contacting Mapbox support](http://www.mapbox.com/contact/support) or opening an issue in the [mapbox-gl-js repo](https://github.com/mapbox/mapbox-gl-js/).
- Mapbox is maintaining this library.
- [mapbox.com/documentation](https://www.mapbox.com/documentation/) should help you find the Mapbox SDKs that exist in other languages. Other third-party developers may have written SDKs for other languages, as well, but I'm not aware.
- Regarding the description of your use case ... I suggest you [contact Mapbox support](http://www.mapbox.com/contact/support) for questions like that.

It doesn't look to me like there's anything wrong with this library, so I'm going to close the issue. Please re-open if you do have a problem that is caused by mapbox-sdk-js. Thanks!

**Comment by devlocalca** [comment]
Thank you for the info.  Mapbox does not advertise this SDK on their main getting started page.  I had to email support to find it or be directed to it.  The 71 lines of warnings and never returning to the command prompt (after 24+ hours) referred to installing the node mapbox sdk they do advertise:

$npm install mapbox-gl --save
--
If there are fully functional code snippets (~5 lines), available for using this SDK, please point me in that direction.  I did not see an /examples/ directory here and the examples given are code snippets missing information and outside of the context of a fully working .js script.  I'm coming up from ground zero and pasting five lines into a file and running, and building from there gets me along quickly.
