### ISSUE TITLE
Dataset API putFeature to upload bulk feature list

### ISSUE THREAD

**Issue by shohil06** [mapbox/mapbox-sdk-js#307]
Hey Team,

I am new to Mapbox, and trying to figure out how do i send my GeoJson of about 300 features to **Mapbox Dataset API** through API since the size of file clearly exceeds 5 MB,

Please let me know any workarounds,

Thanks & Regards,
Shohil Sethia

**Comment by andrewharvey** [comment]
If you just want to run a program use https://github.com/mapbox/send-dataset or https://github.com/mapbox/mapbox-data-cli

If you want to write your own JS app to do it, you'd use this library, using putFeature for each GeoJSON feature.

**Comment by shohil06** [comment]
Hi Andrewharvey, 

Actually i am working on **MapPoint** application, where i will be playing around the **Dataset API** with bulk data, Is there some integrated solution available which i use embed in **Node.js** environment ?

**Comment by andrewharvey** [comment]
@shohil06 Yes that's what this mapbox-sdk-js is for, it abstracts the details of the API away into a Node/JS API. See https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#datasets

**Comment by davidtheclark** [comment]
@shohil06 It sounds like the primary misunderstanding here is about how to push features to the Dataset API. You'll want to push *one feature per request*, instead of trying to push them all in a single request.

You can use this SDK to make the requests that add features to a Dataset — and it should work in Node. But it will not automatically break up your large GeoJSON FeatureCollection into Features and send each one individually. As @andrewharvey stated, you can do that with a Node script.

Since this seems like a question that is not about mapbox-sdk-js but about the Dataset API and tooling more generally, if you would like more followup please contact Mapbox support: https://www.mapbox.com/contact/support

Thanks!
