### ISSUE TITLE
Geocoding two 'types' slows the app down

### ISSUE THREAD

**Issue by lpfunding** [mapbox/mapbox-sdk-js#320]
Dear team,

In our app, users can search for 'poi's and 'places', so McDonalds vs. New York. I am trying to render two types of geocoding results as the following:

3 x 'poi's with close proximity to user 

2 x 'places', with no proximity

If I build two separate geocoders, it slows down the app drastically. Currently my geocoder looks like this, but I almost always only receive 'poi's. How do I change this?

        .forwardGeocode({
          query: this.state.text,
          limit: 5,
          types: ['place', 'poi'],
          proximity: this.props.origin
        })

**Comment by andrewharvey** [comment]
If you pass a proximity option, then it is applied to all types. You would need to make two separate forward geocode calls, one with proximity and one without if you wish to show results from both. The big challenge with that is then working out how to order those results since you no longer get them sorted.

**Comment by danswick** [comment]
Thanks for the great response, @andrewharvey! That's what I would recommend as well. @lpfunding - I'm going to close this issue since it's more about using the geocoding API than `mapbox-sdk-js` itself. If you have any further questions, I'd recommend reaching out to the helpful folk on the Mapbox support team here - https://support.mapbox.com/hc/en-us
