### ISSUE TITLE
confused about `mapId` param in uploads

### ISSUE THREAD

**Issue by vomc** [mapbox/mapbox-sdk-js#336]
Is there a specific reason why `mapId` is required in `uploadsClient.createUpload` ? I noticed that the API itself seems to want a [`tileset` param](https://docs.mapbox.com/api/maps/#create-an-upload)

I am looking to replace a tileset with new vector tiles so currently I am specifying the tileset id as `mapId` ... is this correct?

Thank you! 🙏

**Comment by andrewharvey** [comment]
Yes, in this case the terms Map ID and Tileset ID are interchangeable. Mapbox Studio used to use the term "Map ID", but it recently changed to use the term "Tileset ID", see https://studio.mapbox.com/tilesets/mapbox.mapbox-streets-v8/.

I just updated this in the style spec to use Tileset ID instead of Map ID https://github.com/mapbox/mapbox-gl-js/pull/8915/files

I wonder if it's worth updating this here to tilesetID, as a backwards compatible change (still accept mapID, but hidden from the documentation)?
